plugins {
    id 'checkstyle'
    id 'net.fabricmc.fabric-loom' version "${loom_version}"
    id 'maven-publish'
}

version = project.mod_version
group = project.maven_group

base {
    archivesName = project.archives_base_name
}

loom {
    splitEnvironmentSourceSets()
    mods {
        "obsidian" {
            sourceSet sourceSets.main
            sourceSet sourceSets.client
        }
    }
}

dependencies {
    minecraft "com.mojang:minecraft:${project.minecraft_version}"
    implementation "net.fabricmc:fabric-loader:${project.loader_version}"
    testImplementation "org.junit.jupiter:junit-jupiter:6.1.3"
    testRuntimeOnly "org.junit.platform:junit-platform-launcher:6.1.3"
}

sourceSets {
    test {
        compileClasspath += sourceSets.client.output + sourceSets.client.compileClasspath
        runtimeClasspath += sourceSets.client.output + sourceSets.client.runtimeClasspath
    }
}

tasks.named('test') {
    dependsOn tasks.named('clientClasses')
    useJUnitPlatform()
}

checkstyle {
    toolVersion = '14.3.0'
    ignoreFailures = false
    maxWarnings = 0
}

tasks.withType(org.gradle.api.plugins.quality.Checkstyle).configureEach {
    reports {
        xml.required = true
        html.required = true
    }
}

processResources {
    inputs.property "version", project.version
    filesMatching("fabric.mod.json") {
        expand "version": project.version
    }
}

tasks.withType(JavaCompile).configureEach {
    options.release = 25
    options.encoding = 'UTF-8'
}

java {
    withSourcesJar()
    sourceCompatibility = JavaVersion.VERSION_25
    targetCompatibility = JavaVersion.VERSION_25
}

jar {
    from("NOTICE")
}

publishing {
    publications {
        create("mavenJava", MavenPublication) {
            from components.java
        }
    }
}
