from pathlib import Path

state_path = Path('ai/CURRENT_STATE.md')
roadmap_path = Path('ai/MASTER_ROADMAP.md')

state = state_path.read_text(encoding='utf-8')
old_top = """- **Active milestone: P3.8 — Meshing benchmarks.**\n- Active branch: `phase3/meshing-benchmarks`.\n- Frozen first P3.8 slice: **A-0154 / planned `0.3.0-phase3-dev15`**.\n- Dev15 implementation: **IMPLEMENTED; exact hosted package CI GREEN.**\n- Dev15 implementation review checkpoint: **A-0155**.\n- Dev15 package/runtime handoff: **A-0156**.\n- First dev15 reference benchmark runtime: **A-0157 PARTIAL only because the measured window had `benchmarkResourceReloadDelta=0`; no source/package defect.**\n- Successful dev15 reference benchmark closure: **A-0158 SUCCESS / P3.8 PROMOTION-READY**; `meshingBenchmarkEvidenceReady=true` with measured resource reload, recenter, ordinary rebuild, concurrent worker pressure, coherent bounded percentiles and clean lifetime closure.\n- Exact package validation head: `e6f4b81903ddcdcb859d70a1a01c002a3f550e12`; Build workflow `33270995728` SUCCESS.\n- Canonical dev15 JAR: `Obsidian-0.3.0-phase3-dev15.jar`, 456,609 bytes, SHA-256 `eaad8132665e5f662ac30f5e71abbaff3d604f010e09ffd7aa82379c79a9ed65`.\n- Draft P3.8 PR: **#51**; runtime contract is closed by A-0158, exact synchronized promotion-head CI remains before merge.\n- P3.9 partial remeshing remains out of scope until P3.8 promotion merges and P3.9 is frozen in a new immutable attempt.\n"""
new_top = """- **P3.8 — Meshing benchmarks: COMPLETE through `0.3.0-phase3-dev15`.**\n- Frozen P3.8 contract: **A-0154**; implementation review A-0155; package/runtime handoff A-0156; first runtime A-0157 PARTIAL only for missing measured reload; successful reference baseline A-0158.\n- Canonical dev15 JAR: `Obsidian-0.3.0-phase3-dev15.jar`, 456,609 bytes, SHA-256 `eaad8132665e5f662ac30f5e71abbaff3d604f010e09ffd7aa82379c79a9ed65`.\n- Exact package-validation head `e6f4b81903ddcdcb859d70a1a01c002a3f550e12` passed Build `33270995728`.\n- Exact synchronized P3.8 promotion head `144875e71069f7377a97c78947883592e5c88913` passed Build `33271895037`.\n- Draft PR #51 was closed only because the connected ready-for-review mutation failed on obsolete `Repository.fullDatabaseId`; non-draft same-head PR #52 merged `[no-release]` as `49385aedff74f2382fcd9a9bb44e59cf559e63c4`.\n- **Active milestone: P3.9 — Partial remeshing (EXPERIMENTAL).**\n- P3.9 source work remains blocked until a new immutable contract freeze is recorded from synchronized P3.8-complete `main`.\n"""
if old_top not in state:
    raise SystemExit('CURRENT_STATE top P3.8 anchor mismatch')
state = state.replace(old_top, new_top, 1)
state = state.replace('P3.7 closure remains authoritative. P3.9 partial remeshing remains out of scope while P3.8 is active.',
                      'P3.7 closure remains authoritative. P3.8 is now complete; P3.9 may activate only under a new immutable experimental contract freeze.', 1)
state = state.replace('## ACTIVE: P3.8 — Meshing benchmarks', '## P3.8 — Meshing benchmarks — COMPLETE', 1)
state = state.replace('This is the first trustworthy P3.8 reference baseline. No numerical threshold is retrofitted after seeing it. P3.8 may merge once the synchronized promotion head passes hosted Java 25 / Gradle 9.5.1 Build.',
                      'This is the first trustworthy P3.8 reference baseline. No numerical threshold is retrofitted after seeing it. Exact synchronized promotion head `144875e71069f7377a97c78947883592e5c88913` passed hosted Build `33271895037`; non-draft same-head PR #52 merged `[no-release]` as `49385aedff74f2382fcd9a9bb44e59cf559e63c4`. P3.8 is COMPLETE.', 1)
old_next = """A-0158 closes the frozen P3.8 runtime contract on the exact same canonical dev15 JAR. Require hosted Java 25 / Gradle 9.5.1 Build on the exact synchronized P3.8 promotion head, merge PR #51 `[no-release]` without source/runtime change, then synchronize `main` to P3.8 COMPLETE / P3.9 ACTIVE. After main synchronization, freeze P3.9 partial-remeshing in a new immutable attempt before any P3.9 source change.\n\nDo not implement P3.9 before its contract freeze.\n"""
new_next = """P3.8 is merged and COMPLETE. From the exact synchronized P3.8-complete `main`, create the P3.9 experimental branch and freeze partial-remeshing in a new immutable attempt before any source change. The experiment must prove benefit against the recorded A-0158 full-section baseline while preserving every inherited correctness/lifetime gate and explicitly accounting for metadata, GPU-allocation and fragmentation complexity.\n\nDo not implement P3.9 before its contract freeze.\n"""
if old_next not in state:
    raise SystemExit('CURRENT_STATE immediate action anchor mismatch')
state = state.replace(old_next, new_next, 1)
state_path.write_text(state, encoding='utf-8')

roadmap = roadmap_path.read_text(encoding='utf-8')
old = """#### P3.8 — Meshing benchmarks — ACTIVE\n\nTrack snapshot-to-job latency, P50/P95/P99/max mesh CPU time, input cells, exposed reference faces, greedy rectangles/quads, reduction ratio, vertex/index bytes, scratch high-water, allocations/GC, cancellations/stale jobs and worker utilization.\n\n#### P3.9 — Partial remeshing — EXPERIMENTAL\n\nOnly after full-section greedy meshing is stable and measured. Partial slice/subregion rebuilds must prove enough benefit to justify metadata/fragmentation complexity.\n"""
new = """#### P3.8 — Meshing benchmarks — COMPLETE\n\nA-0158 closes the frozen A-0154 full-section production-mesher baseline on `0.3.0-phase3-dev15`: 305 coherent measured samples with zero collector overflow, queue P50/P95/P99/max `25.7 / 50.5 / 80.0 / 3,683.9 us`, full-ticket execution P50/P95/P99/max `1.001 / 2.664 / 4.432 / 14.408 ms`, real merged workload, measured reload/recenter/rebuild/worker pressure, portable GC/scratch evidence, every inherited P3.7 gate green and clean lifetime. No numerical threshold was retrofitted after measurement. Exact promotion head `144875e71069f7377a97c78947883592e5c88913` passed Build `33271895037`; PR #52 merged `[no-release]` as `49385aedff74f2382fcd9a9bb44e59cf559e63c4`.\n\n#### P3.9 — Partial remeshing — ACTIVE / EXPERIMENTAL\n\nOnly after full-section greedy meshing is stable and measured. Partial slice/subregion rebuilds must prove enough benefit against the recorded A-0158 full-section baseline to justify metadata, scheduling, GPU-allocation and fragmentation complexity. A new immutable contract freeze is mandatory before source changes; fallback to the proven full-section path remains authoritative until the experiment closes.\n"""
if old not in roadmap:
    raise SystemExit('MASTER_ROADMAP P3.8/P3.9 anchor mismatch')
roadmap = roadmap.replace(old, new, 1)
revision_anchor = '## 16. Roadmap revision log\n\n'
revision = """### 2026-08-29 — P3.8 completion and P3.9 activation\n\n- A-0158 closed the frozen A-0154 dev15 benchmark contract on the exact same canonical package after A-0157 was partial only for missing measured F3+T;\n- recorded the first trustworthy full-section baseline with 305/305 retained samples, zero overflow, measured queue/execution distributions, real merged workload, reload/recenter/rebuild pressure, GC/scratch evidence, inherited P3.7 exactness and clean lifetime;\n- exact synchronized P3.8 promotion head `144875e71069f7377a97c78947883592e5c88913` passed hosted Build `33271895037`;\n- draft PR #51 was superseded only because the ready-for-review connector mutation still references invalid `Repository.fullDatabaseId`; non-draft same-head PR #52 merged `[no-release]` as `49385aedff74f2382fcd9a9bb44e59cf559e63c4`;\n- marked P3.8 COMPLETE and activated P3.9 as an EXPERIMENTAL partial-remeshing milestone;\n- require a new immutable P3.9 contract freeze before source changes and retain the full-section path as the fallback/control.\n\n"""
if revision_anchor not in roadmap:
    raise SystemExit('MASTER_ROADMAP revision anchor mismatch')
roadmap = roadmap.replace(revision_anchor, revision_anchor + revision, 1)
roadmap_path.write_text(roadmap, encoding='utf-8')
