from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]

current = ROOT / "ai/CURRENT_STATE.md"
text = current.read_text(encoding="utf-8")
old = '''- Dev17 diagnostic/correction contract: **A-0162 SUCCESS / PLAN FROZEN**. It permits only bounded diagnostics plus correction of source defects proven against permanent P3.7 semantics; provenance surface, admission policy, four-slice layout and every A-0159 threshold are unchanged.\n- Dev17 implementation/package checkpoint: **A-0163 SUCCESS for implementation/package; reference runtime required.** Two dev16 shadow-only correctness defects are corrected: bidirectional visibility/reference equality stronger than permanent P3.7, and raw Minecraft `Direction.ordinal()` vs Obsidian binary-direction comparison.\n- Exact corrected package-validation head `bce641ff08353035d6012fb5c5f5d8c06918da41` / tree `1d6c9a17f089c25f6d70ad9706ba626b2c98eae4` passed hosted Build `33274284466`; canonical dev17 JAR is `Obsidian-0.3.0-phase3-dev17.jar`, 495,236 bytes, SHA-256 `4f8d58251f29742afbc67d95e33a884ea72849fe099a225b154af19616ef7904`.\n- Dev17 final closure now retains exact per-reason fallback counts and the first failed episode fixture (section/episode/mask/edit-count/code/name/index/determinism).\n- Draft P3.9 PR: **#53**; keep draft until the exact dev17 reference runtime closes or rejects A-0159.\n- Dev17 production full-section capture/worker/GPU emission/install/draw remains unchanged; later partial GPU patching is blocked on successful shadow evidence and a separate freeze.\n'''
new = '''- Dev17 diagnostic/correction contract: **A-0162 SUCCESS / PLAN FROZEN**. It permits only bounded diagnostics plus correction of source defects proven against permanent P3.7 semantics; provenance surface, admission policy, four-slice layout and every A-0159 threshold are unchanged.\n- Dev17 implementation/package checkpoint: **A-0163 SUCCESS for implementation/package.** Two dev16 shadow-only correctness defects were corrected: bidirectional visibility/reference equality stronger than permanent P3.7, and raw Minecraft `Direction.ordinal()` vs Obsidian binary-direction comparison.\n- Dev17 reference runtime: **A-0164 PARTIAL**. Correctness is closed at `19/19` exact with zero correctness/unselected/determinism failures and all inherited/lifetime gates green, but evidence volume was `19/32`, one-slice `14/16`, two-slice `5/8`, coalesced `0/1`. Fallback accounting proved provenance `0` and multi-section `0`, with dominant avoidable losses pending `9` and not-LIVE `19`. Projected upload P50/P95 remained adverse at `1000/1000` permille and is retained unchanged as evidence.\n- Dev18 pending-coalescing contract: **A-0165 SUCCESS / PLAN FROZEN**. Same-section exact localized dirty provenance may widen one pending immutable shadow episode across production rebuild generations while preserving the original pre-edit slice fingerprints; global/ambiguous/cross-section/halo/all-slice cases still fall back full-section. Every A-0159 threshold remains unchanged.\n- Dev18 implementation/package checkpoint: **A-0166 SUCCESS for implementation/package; reference runtime required.** Exact package-validation head `cfff336b1cb8ab18214d48af3521f65c4182acb3` / tree `90f0a44bf811ac1c3dc6e0965ad7de8d01894693` passed hosted Build `33275004099`; canonical dev18 JAR is `Obsidian-0.3.0-phase3-dev18.jar`, 496,542 bytes, SHA-256 `cb3065a172489f197ee3f3b988fe3f202a8079ee6bafb87516f24d65d7fdf8a1`.\n- Dev18 result completion requires exact episode id plus final widened slice mask, preventing an older narrow worker result from closing a widened pending episode; request self-tests prove mask union, edit accounting, fingerprint preservation, all-four rejection and overflow rejection.\n- Draft P3.9 PR: **#53**; keep draft until the exact dev18 reference runtime closes or rejects A-0159.\n- Dev18 production full-section capture/worker/GPU emission/install/draw remains unchanged; later partial GPU patching is blocked on successful shadow evidence and a separate freeze.\n'''
if text.count(old) != 1:
    raise RuntimeError("CURRENT_STATE dev17 block not found exactly")
current.write_text(text.replace(old, new, 1), encoding="utf-8")

attempt = ROOT / "ai/ATTEMPT_LOG.md"
log = attempt.read_text(encoding="utf-8").rstrip() + "\n"
entries = []
if "## A-0164 -" not in log:
    entries.append('''\n---\n\n## A-0164 - P3.9 dev17 reference runtime partial\n\n**Date:** 2026-08-29\n**Objective:** Evaluate the exact canonical dev17 diagnostic/correction package against unchanged A-0159.\n**Action:** Reference runtime exercised localized edits, F3+T, real recenter and normal shutdown.\n**Result:** `PARTIAL`.\n**Actual effect:** Dev17 closed correctness at 19/19 exact with zero correctness, unselected-change or determinism failures; all inherited and lifetime gates remained green. Evidence volume remained short at 19/32 localized, 14/16 one-slice, 5/8 two-slice and 0/1 coalesced. Fallback diagnostics showed provenance=0, multi-section=0, halo/boundary=7, pending=9 and not-LIVE=19. CPU thresholds passed; projected upload remained 1000/1000 permille but cannot formally reject the strategy before frozen evidence volume closes.\n**Evidence:** `ai/attempts/A-0164-phase3-p3.9-dev17-reference-runtime-partial.md`.\n**Lesson:** Do not rerun unchanged dev17; correct the shadow episode state machine so exact same-section edits can survive pending/non-LIVE rebuild intervals.\n''')
if "## A-0165 -" not in log:
    entries.append('''\n---\n\n## A-0165 - P3.9 dev18 pending-coalescing contract freeze\n\n**Date:** 2026-08-29\n**Objective:** Freeze the smallest correction justified by A-0164 before source changes.\n**Action:** Allow only exact same-section localized dirty provenance to widen one pending immutable request across rebuild generations while preserving original pre-edit fingerprints; keep global/ambiguous/cross-section/halo/all-slice fallback behavior and every A-0159 threshold unchanged.\n**Result:** `SUCCESS` / `PLAN FROZEN`.\n**Evidence:** `ai/attempts/A-0165-phase3-p3.9-dev18-pending-coalescing-contract.md`.\n**Next action:** Implement exactly the frozen correction, package in hosted CI, then run the unchanged reference workload.\n''')
if "## A-0166 -" not in log:
    entries.append('''\n---\n\n## A-0166 - P3.9 dev18 pending-coalescing implementation and package\n\n**Date:** 2026-08-29\n**Objective:** Produce the exact dev18 runtime package without changing production rendering or frozen A-0159 thresholds.\n**Action:** Added immutable pending request coalescing with original-fingerprint retention, exact mask/edit union, all-four/overflow rejection and final result id+mask matching; production paths and benefit accounting remain unchanged.\n**Result:** `SUCCESS` for implementation/package; reference runtime required.\n**Evidence:** `ai/attempts/A-0166-phase3-p3.9-dev18-pending-coalescing-package.md`; exact validation head `cfff336b1cb8ab18214d48af3521f65c4182acb3`, Build `33275004099`, artifact `9721228593`; canonical dev18 JAR 496,542 bytes, SHA-256 `cb3065a172489f197ee3f3b988fe3f202a8079ee6bafb87516f24d65d7fdf8a1`.\n**Next action:** Run the exact dev18 package through unchanged A-0159. If evidence volume closes and upload P50/P95 remains above 600/800 permille, reject/redesign the fixed four-slice strategy rather than retuning thresholds.\n''')
if entries:
    attempt.write_text(log + "".join(entries).lstrip(), encoding="utf-8")

print("dev18 continuity synchronized")
