from pathlib import Path

state_path = Path('ai/CURRENT_STATE.md')
state = state_path.read_text()
old_top = """- Frozen first P3.9 slice: **A-0159 / planned `0.3.0-phase3-dev16`** — shadow-only four fixed Y slices, exact block-local dirty provenance with mandatory full fallback, matched full-section control and pre-frozen benefit/complexity thresholds.\n- Dev16 production GPU emission/install remains unchanged; later partial GPU patching is blocked on successful shadow evidence and a separate contract.\n"""
new_top = """- Frozen first P3.9 slice: **A-0159 / `0.3.0-phase3-dev16`** — shadow-only four fixed Y slices, exact block-local dirty provenance with mandatory full fallback, matched full-section control and pre-frozen benefit/complexity thresholds.\n- Dev16 implementation/package checkpoint: **A-0160 SUCCESS for implementation/package; reference runtime required.**\n- Exact clean package-validation head `9b5930a24c8bd1841c474a03f67407231e11bc65` passed hosted Build `33273077105`; canonical dev16 JAR is `Obsidian-0.3.0-phase3-dev16.jar`, 490,250 bytes, SHA-256 `b14640ab1a397561371564e6b3c38b93b105e481be6a32b8172b8448de701ffd`.\n- Draft P3.9 PR: **#53**; keep draft until the exact A-0159 reference runtime proves or rejects the frozen experiment thresholds.\n- Dev16 production GPU emission/install remains unchanged; later partial GPU patching is blocked on successful shadow evidence and a separate contract.\n"""
if state.count(old_top) != 1:
    raise SystemExit('CURRENT_STATE top anchor mismatch')
state = state.replace(old_top, new_top, 1)
old_next = """## Immediate next action\n\nA-0159 freezes the first P3.9 experiment before source changes. Implement dev16 in shadow mode only: exact bounded block-local dirty provenance; deterministic four-slice mask/dependency planning; shadow slice meshing/proofs over existing immutable captured truth; unselected-slice under-invalidation fingerprints; matched shadow/full-section timing/work/output telemetry; and the frozen decision gate. Keep production full-section GPU emission/install authoritative and unchanged.\n\nDo not implement partial GPU patching in dev16.\n"""
new_next = """## ACTIVE: P3.9 — Partial remeshing experiment\n\nA-0159 freezes dev16 as a shadow-only four-slice experiment. A-0160 records the implemented/package-validated result. Exact package authority is head `9b5930a24c8bd1841c474a03f67407231e11bc65`, Build `33273077105`, canonical direct JAR `Obsidian-0.3.0-phase3-dev16.jar`, 490,250 bytes, SHA-256 `b14640ab1a397561371564e6b3c38b93b105e481be6a32b8172b8448de701ffd`. Production remains the unchanged full-section renderer.\n\nDev16 now includes exact block-local dirty provenance, fixed four-slice shadow requests, previous/current per-slice truth fingerprints, selected source/reference/render-equivalence proofs, deterministic double-build shadow projection, matched full-production execution/upload controls, bounded percentile/ratio telemetry and the pre-frozen A-0159 decision gate. No shadow output is uploaded or rendered.\n\n## Immediate next action\n\nRun the exact canonical dev16 JAR under A-0159/A-0160. After the explicit P3.9 shadow-window arm, collect at least 32 localized episodes including at least 16 one-slice, 8 two-slice and one coalesced episode; include post-arm F3+T and a real scene recenter as full-fallback exercises; require every inherited P3.8/P3.7/lifetime gate and all dev16 correctness gates to remain clean. The frozen benefit/complexity thresholds decide whether P3.9 advances, is rejected/deferred, or is redesigned in a new immutable attempt.\n\nDo not implement partial GPU patching unless the shadow experiment first passes and a separate contract is frozen.\n"""
if state.count(old_next) != 1:
    raise SystemExit('CURRENT_STATE immediate-action anchor mismatch')
state_path.write_text(state.replace(old_next, new_next, 1))

log_path = Path('ai/ATTEMPT_LOG.md')
log = log_path.read_text()
entry = """\n- **A-0160** — P3.9 dev16 shadow partial-remeshing implementation/package: A-0159 implemented without production render/GPU-install changes; corrected helper Build `33272993694` compiled the clean source; exact clean package head `9b5930a24c8bd1841c474a03f67407231e11bc65` passed hosted Build `33273077105`; canonical direct dev16 JAR is 490,250 bytes, SHA-256 `b14640ab1a397561371564e6b3c38b93b105e481be6a32b8172b8448de701ffd`. Reference runtime/threshold decision remains required; PR #53 stays draft. See `ai/attempts/A-0160-phase3-p3.9-dev16-implementation-package.md`.\n"""
if '**A-0160**' in log:
    raise SystemExit('ATTEMPT_LOG already contains A-0160')
log_path.write_text(log.rstrip() + entry + '\n')
